server:
  port: 9000
  
  ssl:    key-store: ssl/keystore.p12
    key-store-password: 12345678
    key-store-type: PKCS12
    key-alias: tomcat
    
logging:
  level:
    com.example: INFO
  pattern:    console: "%d{HH-mm-ss.SSS} [%-5p] [%-30t] : %m%n%rEx"